name = "realthx1/luaulog"
version = "0.2.0"
description = "Fast and easy-to-use logging library for Roblox"
authors = ["realthx1"]
repository = "https://github.com/realthx1/luaulog"
license = "MIT"
includes = ["src/**/*.luau", "pesde.toml", "README.md", "LICENSE", ".luaurc"]

[target]
environment = "roblox"
build_files = ["src/init.luau"]
lib = "src/init.luau"

[indices]
default = "https://github.com/pesde-pkg/index"
